# Generated by Django 4.2.4 on 2023-08-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfile', '0002_usercsvfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop1', models.CharField(max_length=100)),
                ('shop2', models.CharField(max_length=100)),
                ('total_inventary', models.IntegerField()),
                ('minimum_stock', models.IntegerField()),
            ],
        ),
    ]
